language: python
python:
    - "2.7"
cache:
  - directories:
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
    - $HOME/.pip-cache
  - apt
before_install:
  - echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
  - sudo apt-get install python-dev
install:
  - python setup.py install
  - pip install -r dev-requirements.txt
script: "nosetests -v"
